### PR TITLE
allow handling of types like null.String

### PR DESCRIPTION
**Pull request by HenrikPihl**

### CODE REVIEW

**Comment by alexcesaro** [comment]
Thanks, could you add a test that failed before this PR?

**Comment by HenrikPihl** [comment]
Nothing failed, the issue is that types from
gopkg.in/guregu/null.v2
are structs and marshalled as such, and that does not look right in a csv
export.

**Comment by alexcesaro** [comment]
I would like this new feature to be tested. So please add a test that expects an object implementing `encoding.TextMarshaler` to be marshalled using that method.
This new test should fail before your PR (and should now pass).

**Comment by HenrikPihl** [comment]
Test added and pushed

**Comment by alexcesaro** [comment]
Thanks. I simplified and merged your code.

**Pull request closed without merging**
